/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as Char123LocaleChar125ShopRouteImport } from './routes/{-$locale}/shop'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProductStatsRouteImport } from './routes/admin.product-stats'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminI18nRouteImport } from './routes/admin.i18n'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBridgeCheckRouteImport } from './routes/admin.bridge-check'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminAbTestsRouteImport } from './routes/admin.ab-tests'
import { Route as Char123LocaleChar125PSlugRouteImport } from './routes/{-$locale}/p.$slug'
import { Route as Char123LocaleChar125LegalSlugRouteImport } from './routes/{-$locale}/legal.$slug'
import { Route as ApiPublicHooksSitemapRefreshRouteImport } from './routes/api/public/hooks/sitemap-refresh'
import { Route as ApiPublicHooksCronRouteImport } from './routes/api/public/hooks/cron'
import { Route as ApiPublicHooksCapResetRouteImport } from './routes/api/public/hooks/cap-reset'
import { Route as ApiPublicBridgeCallbackRouteImport } from './routes/api/public/bridge/callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const Char123LocaleChar125ShopRoute =
  Char123LocaleChar125ShopRouteImport.update({
    id: '/{-$locale}/shop',
    path: '/{-$locale}/shop',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductStatsRoute = AdminProductStatsRouteImport.update({
  id: '/product-stats',
  path: '/product-stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminI18nRoute = AdminI18nRouteImport.update({
  id: '/i18n',
  path: '/i18n',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBridgeCheckRoute = AdminBridgeCheckRouteImport.update({
  id: '/bridge-check',
  path: '/bridge-check',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbTestsRoute = AdminAbTestsRouteImport.update({
  id: '/ab-tests',
  path: '/ab-tests',
  getParentRoute: () => AdminRoute,
} as any)
const Char123LocaleChar125PSlugRoute =
  Char123LocaleChar125PSlugRouteImport.update({
    id: '/{-$locale}/p/$slug',
    path: '/{-$locale}/p/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LegalSlugRoute =
  Char123LocaleChar125LegalSlugRouteImport.update({
    id: '/{-$locale}/legal/$slug',
    path: '/{-$locale}/legal/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSitemapRefreshRoute =
  ApiPublicHooksSitemapRefreshRouteImport.update({
    id: '/api/public/hooks/sitemap-refresh',
    path: '/api/public/hooks/sitemap-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCronRoute = ApiPublicHooksCronRouteImport.update({
  id: '/api/public/hooks/cron',
  path: '/api/public/hooks/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCapResetRoute = ApiPublicHooksCapResetRouteImport.update({
  id: '/api/public/hooks/cap-reset',
  path: '/api/public/hooks/cap-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCallbackRoute = ApiPublicBridgeCallbackRouteImport.update({
  id: '/api/public/bridge/callback',
  path: '/api/public/bridge/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/bridge-check': typeof AdminBridgeCheckRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/i18n': typeof AdminI18nRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/product-stats': typeof AdminProductStatsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/sync': typeof AdminSyncRoute
  '/{-$locale}/shop': typeof Char123LocaleChar125ShopRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/legal/$slug': typeof Char123LocaleChar125LegalSlugRoute
  '/{-$locale}/p/$slug': typeof Char123LocaleChar125PSlugRoute
  '/api/public/bridge/callback': typeof ApiPublicBridgeCallbackRoute
  '/api/public/hooks/cap-reset': typeof ApiPublicHooksCapResetRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/sitemap-refresh': typeof ApiPublicHooksSitemapRefreshRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/bridge-check': typeof AdminBridgeCheckRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/i18n': typeof AdminI18nRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/product-stats': typeof AdminProductStatsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/sync': typeof AdminSyncRoute
  '/{-$locale}/shop': typeof Char123LocaleChar125ShopRoute
  '/admin': typeof AdminIndexRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/legal/$slug': typeof Char123LocaleChar125LegalSlugRoute
  '/{-$locale}/p/$slug': typeof Char123LocaleChar125PSlugRoute
  '/api/public/bridge/callback': typeof ApiPublicBridgeCallbackRoute
  '/api/public/hooks/cap-reset': typeof ApiPublicHooksCapResetRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/sitemap-refresh': typeof ApiPublicHooksSitemapRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/bridge-check': typeof AdminBridgeCheckRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/i18n': typeof AdminI18nRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/product-stats': typeof AdminProductStatsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/sync': typeof AdminSyncRoute
  '/{-$locale}/shop': typeof Char123LocaleChar125ShopRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/legal/$slug': typeof Char123LocaleChar125LegalSlugRoute
  '/{-$locale}/p/$slug': typeof Char123LocaleChar125PSlugRoute
  '/api/public/bridge/callback': typeof ApiPublicBridgeCallbackRoute
  '/api/public/hooks/cap-reset': typeof ApiPublicHooksCapResetRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/sitemap-refresh': typeof ApiPublicHooksSitemapRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ab-tests'
    | '/admin/branding'
    | '/admin/bridge-check'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/i18n'
    | '/admin/legal'
    | '/admin/logs'
    | '/admin/performance'
    | '/admin/product-stats'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/sync'
    | '/{-$locale}/shop'
    | '/admin/'
    | '/{-$locale}/'
    | '/{-$locale}/legal/$slug'
    | '/{-$locale}/p/$slug'
    | '/api/public/bridge/callback'
    | '/api/public/hooks/cap-reset'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/sitemap-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ab-tests'
    | '/admin/branding'
    | '/admin/bridge-check'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/i18n'
    | '/admin/legal'
    | '/admin/logs'
    | '/admin/performance'
    | '/admin/product-stats'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/sync'
    | '/{-$locale}/shop'
    | '/admin'
    | '/{-$locale}'
    | '/{-$locale}/legal/$slug'
    | '/{-$locale}/p/$slug'
    | '/api/public/bridge/callback'
    | '/api/public/hooks/cap-reset'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/sitemap-refresh'
  id:
    | '__root__'
    | '/admin'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ab-tests'
    | '/admin/branding'
    | '/admin/bridge-check'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/i18n'
    | '/admin/legal'
    | '/admin/logs'
    | '/admin/performance'
    | '/admin/product-stats'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/sync'
    | '/{-$locale}/shop'
    | '/admin/'
    | '/{-$locale}/'
    | '/{-$locale}/legal/$slug'
    | '/{-$locale}/p/$slug'
    | '/api/public/bridge/callback'
    | '/api/public/hooks/cap-reset'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/sitemap-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125ShopRoute: typeof Char123LocaleChar125ShopRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125LegalSlugRoute: typeof Char123LocaleChar125LegalSlugRoute
  Char123LocaleChar125PSlugRoute: typeof Char123LocaleChar125PSlugRoute
  ApiPublicBridgeCallbackRoute: typeof ApiPublicBridgeCallbackRoute
  ApiPublicHooksCapResetRoute: typeof ApiPublicHooksCapResetRoute
  ApiPublicHooksCronRoute: typeof ApiPublicHooksCronRoute
  ApiPublicHooksSitemapRefreshRoute: typeof ApiPublicHooksSitemapRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/{-$locale}/shop': {
      id: '/{-$locale}/shop'
      path: '/{-$locale}/shop'
      fullPath: '/{-$locale}/shop'
      preLoaderRoute: typeof Char123LocaleChar125ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-stats': {
      id: '/admin/product-stats'
      path: '/product-stats'
      fullPath: '/admin/product-stats'
      preLoaderRoute: typeof AdminProductStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/i18n': {
      id: '/admin/i18n'
      path: '/i18n'
      fullPath: '/admin/i18n'
      preLoaderRoute: typeof AdminI18nRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bridge-check': {
      id: '/admin/bridge-check'
      path: '/bridge-check'
      fullPath: '/admin/bridge-check'
      preLoaderRoute: typeof AdminBridgeCheckRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ab-tests': {
      id: '/admin/ab-tests'
      path: '/ab-tests'
      fullPath: '/admin/ab-tests'
      preLoaderRoute: typeof AdminAbTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/{-$locale}/p/$slug': {
      id: '/{-$locale}/p/$slug'
      path: '/{-$locale}/p/$slug'
      fullPath: '/{-$locale}/p/$slug'
      preLoaderRoute: typeof Char123LocaleChar125PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/legal/$slug': {
      id: '/{-$locale}/legal/$slug'
      path: '/{-$locale}/legal/$slug'
      fullPath: '/{-$locale}/legal/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sitemap-refresh': {
      id: '/api/public/hooks/sitemap-refresh'
      path: '/api/public/hooks/sitemap-refresh'
      fullPath: '/api/public/hooks/sitemap-refresh'
      preLoaderRoute: typeof ApiPublicHooksSitemapRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron': {
      id: '/api/public/hooks/cron'
      path: '/api/public/hooks/cron'
      fullPath: '/api/public/hooks/cron'
      preLoaderRoute: typeof ApiPublicHooksCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cap-reset': {
      id: '/api/public/hooks/cap-reset'
      path: '/api/public/hooks/cap-reset'
      fullPath: '/api/public/hooks/cap-reset'
      preLoaderRoute: typeof ApiPublicHooksCapResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/callback': {
      id: '/api/public/bridge/callback'
      path: '/api/public/bridge/callback'
      fullPath: '/api/public/bridge/callback'
      preLoaderRoute: typeof ApiPublicBridgeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAbTestsRoute: typeof AdminAbTestsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminBridgeCheckRoute: typeof AdminBridgeCheckRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminI18nRoute: typeof AdminI18nRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminProductStatsRoute: typeof AdminProductStatsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbTestsRoute: AdminAbTestsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminBridgeCheckRoute: AdminBridgeCheckRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminI18nRoute: AdminI18nRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminProductStatsRoute: AdminProductStatsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125ShopRoute: Char123LocaleChar125ShopRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125LegalSlugRoute: Char123LocaleChar125LegalSlugRoute,
  Char123LocaleChar125PSlugRoute: Char123LocaleChar125PSlugRoute,
  ApiPublicBridgeCallbackRoute: ApiPublicBridgeCallbackRoute,
  ApiPublicHooksCapResetRoute: ApiPublicHooksCapResetRoute,
  ApiPublicHooksCronRoute: ApiPublicHooksCronRoute,
  ApiPublicHooksSitemapRefreshRoute: ApiPublicHooksSitemapRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
